[package]
name = "iara"
version = "0.1.0"
edition = "2021"
description = "Organize text to turn its util"



# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
